## Numpy

In [1]:
!pip install numpy

In [4]:
import time
import numpy as np

size = 10000000
#for list
a = list(range(size))
start_l = time.time()
a = list(map(lambda i : i**2, a))
end_l = time.time() - start_l

#array
a = np.arange(size)
start_a = time.time()
a = [a**2]
end_a = time.time() - start_a

print("Time take by list:",end_l)
print("Time take by array",end_a)


Time take by list: 2.714252471923828
Time take by array 0.041611671447753906


In [1]:
# 11/9/26
import numpy as np

# function accepts objects/parameter
# 

In [3]:
# How to Create Array ---------- ans - .array()

a = [12,34,56]
print(type(a))
print(a)

<class 'list'>
[12, 34, 56]


In [8]:
# Creating array using list

arr = np.array(a)
print(arr)
print(type(arr))

[12 34 56]
<class 'numpy.ndarray'>


In [7]:
arr1 = np.array([10,30,50,8])
print(arr1)

[10 30 50  8]


In [9]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Array Attribute
# 1. ndim - to check the dimension of an array
# 2. shape - to check the row and coloumn 
# 3. size - to check the size of an array
# 4. dtype - it show the data type of array
# 5. itemsize -  it shows how much memory taken by one element of an array

In [14]:
print(arr2.ndim)  # it shows the dimension of the array

1


In [12]:
print(arr2.shape) # it shows matrix format of array - 4 row and 1 column

(10,)


In [24]:
print(arr2.size)

10


In [25]:
arr3 = np.array([1,2,3])
arr4 = np.array([1.2,2.3,3.1])
arr5 = np.array([16,241.3,'1'])
print(arr3,arr4,arr5)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)

# U32 here U is Unicode

[1 2 3] [1.2 2.3 3.1] ['16' '241.3' '352300']
int64
float64
<U32


In [34]:
print(arr5.itemsize)

str_array = np.array(["12","34",45])
float_array = np.array([12.45,89,90.3,2])
int_array = np.array([12,5,45])

print(str_array.itemsize)
print(float_array.itemsize)
print(int_array.itemsize)


128
84
8
8


In [36]:
# create an array on integer of 5 element

arr6 = np.array([12,56,7,36,58])
print((arr6.itemsize)*(arr6.size))

40


In [ ]:
# task for python libraries

# 1. create an array containg element 1 to 15 
# 2. create an array of mixed data type containing 4 element and tell what data type will array change and why
# 3. on the above created array find the data types of elements
# 4. create a array of size 7 and print size
# 5. create an array of first 5 even number and print size, datatype, total memory of array, shape of array, and which dimension of the array is and also write one line defination what attri

In [2]:
import numpy as np

arrrr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arrrr) 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# 15/9/2026

In [9]:
# How to create 2d array

import numpy as np

arr = np.array([[10,20],[40,50],[30,60]])
print(arr)
print(arr.shape)
print(arr.itemsize)

[[10 20]
 [40 50]
 [30 60]]
(3, 2)
8


In [18]:
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
2
9


In [17]:
# arr3 = np.arange(1,101)
# print(np.array(arr3))

print(np.array(np.arange(1,101)))
print(arr2.itemsize)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
8


In [17]:
print(np.array(np.arange(0,51,5)))

[ 0  5 10 15 20 25 30 35 40 45 50]


In [20]:
print(np.array(np.arange(2,21,2)))

[ 2  4  6  8 10 12 14 16 18 20]


In [21]:
# create a 2d array for the following shape manlly
# 1,1 2,6 3,1 1,6 

# create a 1d array starting from 0 to 100 with step size of 10
# create a 1d array containing 20 first odd numbers
# create a 2d array of 3,3 and perform all 5 attributes of array
# find difference b/w python range function and numpy arange function

In [7]:
import numpy as np

arr1 = np.array([[1]])
print(arr1)
print(np.array(np.arange(1,40,2)))

[[1]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [ ]:
# 16/9/2026

In [ ]:
# Creating 2d array using numpy functions

In [2]:
import numpy as np

a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# -------- reshape ---------


In [5]:
ar = np.arange(1,10).reshape(3,3)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.arange(1,82).reshape(9,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [ ]:
# ------- random ---------
# it give random value b/w 0-1 

In [13]:
print(np.random.random(20))
print(np.random.random(20).reshape(4,5))


[0.22058326 0.69531884 0.08639606 0.12165091 0.34270089 0.1167852
 0.17917289 0.36507804 0.24790642 0.20291121 0.79540927 0.65158898
 0.54024604 0.22154563 0.59676196 0.47669166 0.30363226 0.11834657
 0.93070009 0.03154453]
[[0.84007642 0.0387541  0.59646081 0.63645323 0.37813378]
 [0.05471521 0.06459087 0.65914251 0.34791838 0.05597342]
 [0.26303384 0.99609793 0.15871474 0.80377934 0.42311668]
 [0.33786067 0.74516724 0.96888311 0.45092154 0.7768783 ]]


In [15]:
# randint - it give single random integer

print(np.random.randint(12))

7


In [53]:
print(np.random.randint(12,45,7).reshape(7,1))

[[18]
 [19]
 [37]
 [26]
 [19]
 [20]
 [17]]


In [57]:
# create a array of random integer rumber of 1-51 and reshape the array to all possible shape

print(np.random.randint(1,51,36).reshape(6,6))
print(np.random.randint(1,51,36).reshape(9,4))
print(np.random.randint(1,51,36).reshape(4,9))
print(np.random.randint(1,51,36).reshape(2,18))
print(np.random.randint(1,51,36).reshape(18,2))
print(np.random.randint(1,51,36).reshape(12,3))
print(np.random.randint(1,51,36).reshape(3,12))
print(np.random.randint(1,51,36).reshape(1,36))
print(np.random.randint(1,51,36).reshape(36,1))


[[31 12 15 24 36 40]
 [39 26 20 48 24  5]
 [31 23 16 38 21 34]
 [ 3  1 12 47  5  6]
 [ 7 14 21 21 50 37]
 [40  7 50 33 21 46]]
[[ 8 40 34 38]
 [29 41  1 14]
 [ 7 42 32  4]
 [14 42 25 13]
 [ 9 43 28 17]
 [ 3 24 26 29]
 [36 18 16 18]
 [25 50 32 14]
 [44  7 15 41]]
[[ 7 34  1 26 30 24 14  4 27]
 [ 4 36 11 41 40  7 44  3  1]
 [13 26 14 43 29  1 34  9 42]
 [17  3 26 38 21  6  3 39 26]]
[[24  7 19  5  8 41 32 39 30  3  6 50 42 20  7  3 47 10]
 [14 31 49 19 41 30 35 19 18 45 36 46 37  7 18 14  4 26]]
[[37 49]
 [18 20]
 [20 10]
 [42 17]
 [38  4]
 [18 36]
 [18 50]
 [38 40]
 [ 7 50]
 [30 32]
 [21 34]
 [41 25]
 [45 28]
 [10 29]
 [10 28]
 [49 17]
 [14 28]
 [37 49]]
[[20 41  3]
 [12  4 42]
 [ 2 39 48]
 [34 46 37]
 [10  7 25]
 [23 38 35]
 [50 29 22]
 [26  2 34]
 [ 1 23 23]
 [ 9 38  4]
 [29 34 10]
 [ 3 10  4]]
[[34 31 39 29 41 36 28 13 41 14 28  1]
 [10 44 10 13 38  8 22 23 34 13 14 36]
 [ 1 49 35 19 31 28 47 50 35 11  5  4]]
[[50 45 17 18 22 45 26 22 12 46 38 47 47 18  4 27 36  2 30 38 42 13 31 43
 

In [ ]:
# -------- zeros --------

In [65]:
print(np.zeros(4).reshape(2,2))
print(np.zeros((2,9)))

[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
# create a of zeros in matrix formate 5,5 using first reshape and again without using reshape
print(np.zeros(25).reshape(5,5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [71]:
# ones

print(np.ones((5,3)))
print(np.ones(9).reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
print(np.ones((3,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [3]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 17/9/2026

In [8]:
# How to Create identity matrix 

import numpy as np
# print(np.eye(2))
print(np.eye(4,dtype=int))          # np.eye is use to create identity matrix

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
print(np.random.randint(12,34,(4,5)))

[[29 31 12 18 16]
 [12 32 14 23 18]
 [25 20 17 19 31]
 [25 15 31 18 15]]


In [30]:
# Indexing 

arr = np.random.randint(12,34,(3,3))
print(arr)

[[14 12 26]
 [30 19 28]
 [27 31 26]]


In [33]:
print(arr[1,0])


30


In [34]:
# Boolean Indexing :- condition ke base ke data ko filter karna

print(arr)

[[14 12 26]
 [30 19 28]
 [27 31 26]]


In [36]:
print(arr[arr>20])

[26 30 28 27 31 26]


In [37]:
print(arr[arr%2==0])

[14 12 26 30 28 26]


In [40]:
ab = np.random.randint(12,34,(3,5))
print(ab)
print(ab[0: ,1:2])

[[20 24 18 13 15]
 [21 15 14 33 17]
 [33 31 19 21 13]]
[[24]
 [15]
 [31]]


In [ ]:
# Create a 3,3 matrix and the filter the values divisible by 2
# Create a 4,4 matrix of even number and odd number
# Create a following matrix int zeros 4,4 matrix and make border of 1
# create a 3,3 matrix of int 5 number
